# Use postgres/example user/password credentials
version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      APP_USERNAME: admin
      APP_PASSWORD: admin
      DATABASE_URL: 'postgresql://sharewarez:!Piratingin2024!@db/sharewarez'
    depends_on:
      - db     
  db:
    image: postgres:16.2
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: sharewarez
      POSTGRES_PASSWORD: '!Piratingin2024!'
      POSTGRES_DB: sharewarez
    ports:
      - "5432:5432"
